# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c78434a4d591b2a45234247033697d19ddffa7c299b30d1e6bfa372d57ec9cd55e69afe1ae92619dc34341d57fae5851536ff7a16a5bee9ea073132c954e93a1

test:
  secret_key_base: 2023ae2bcad5dc44f100404a40ffde39cc184b6a16f404d99d0fc57c3e5143edad1f7ae8da14259d4f71babb36e12d45247bfb7948aa34f22cd615a47c69b3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
